version: '3.7'
services:
  minecraft:
    image: 'itzg/minecraft-server'
    restart: always
    environment:
      EULA: 'TRUE'
      MEMORY: '3G'
      OVERRIDE_SERVER_PROPERTIES: 'true'
      MOTD: 'Not the bees!!!'
      DIFFICULTY: 'normal'
      SEED: '-929179197546132'
      OPS: 'mbeoiosttieer'
    ports:
      - '25565:25565'
    volumes:
      - 'minecraft_data:/data'
      - './me_mcserver.png:/data/server-icon.png'
  jobber:
    image: 'jobber'
    command: |
      /bin/sh -c '/bin/chmod 644 /home/jobberuser/.jobber \
      && /usr/libexec/jobberrunner -u /var/jobber/1000/cmd.sock /home/jobberuser/.jobber'
    volumes:
      - './jobber.yml:/home/jobberuser/.jobber'
      - 'minecraft_data:/backup_source'
      - '/efs/minecraft-backups:/backup_dest'
  overviewer:
    build: ./overviewer
    volumes:
      - './overviewer-cron:/etc/cron.d/'
volumes:
  minecraft_data:
    name: 'minecraft_data'
