version: '3.7'
services:
  minecraft:
    image: 'itzg/minecraft-server'
    restart: always
    environment:
      EULA: 'TRUE'
    ports:
      - '25565:25565'
    volumes:
      - 'minecraft_data:/data'

volumes:
  minecraft_data:
    name: 'minecraft_data'
