version: 1.4

jobs:
  MinuteTest:
    cmd: |
      echo 'Creating backup'
      tar -czf /backup_dest/minecraft_backup_$(date +%Y%m%d%H%M%S).tar.gz /backup_source/
      find /efs/minecraft-backups -ctime +20
      echo 'Done.'
    time: 0 0 8
